dist: trusty
sudo: required
services:
  - docker
language: python
install:
  - sudo apt-get install -y libffi-dev build-essential python-dev
  - sudo pip install ansible
script:
  - sudo ansible-playbook -i localhost, -c local provisioning/deployment.yml
