dist: trusty
sudo: required
language: generic
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -y libffi-dev build-essential python-dev
  - sudo pip install ansible
script:
  - sudo ln -s `pwd`/project /vagrant
  - ansible-playbook -vvvv --become -i localhost, -c local -e "system_skip_full_upgrade=yes" provisioning/deployment.yml
