dist: trusty
sudo: required
language: python
install:
  - sudo apt-get install -y libffi-dev build-essential python-dev
  - sudo pip install ansible
script:
  - sudo ln -s `pwd`/project /vagrant
  - sudo -E ansible-playbook -vvv -i localhost, -c local -e "system_skip_full_upgrade=yes" provisioning/deployment.yml
