---
- name: "Install Mesos"
  apt: name="{{item}}" state=present update_cache=yes
  with_items:
    - mesos
- name: "Configure containerizers"
  lineinfile: line="docker,mesos" dest=/etc/mesos-slave/containerizers state=present create=yes
- name: "Configure networking (IP)"
  lineinfile: >
    line={{ansible_default_ipv4.address}}
    create=yes
    dest={{item}}
  with_items:
    - /etc/mesos-master/ip
    - /etc/mesos-slave/ip
- name: "Configure networking (hostname)"
  lineinfile: >
    line={{ansible_hostname}}
    create=yes
    dest={{item}}
  with_items:
    - /etc/mesos-master/hostname
    - /etc/mesos-slave/hostname
- name: "Configure Zookeeper"
  shell: "echo 'zk://localhost:2181/mesos' > /etc/mesos/zk"
- name: Restart Zookeeper and Mesos
  service: name="{{item}}" state=restarted
  with_items:
    - zookeeper
    - mesos-master
    - mesos-slave
- name: Waiting for ports to become available (Zookeeper, Mesos)
  wait_for: >
    port={{item}}
    host={{ansible_default_ipv4.address}}
    delay=2
  with_items:
    - 2181
    - 5050

