---
- name: "Install Marathon"
  apt: name="{{item}}" state=present update_cache=yes
  with_items:
    - marathon
  register: var_marathon_installation
- name: Delete Marathon tasks
  uri: 
    url: "{{ marathon_api_base_url ~ '/apps/' ~ ((item|from_json).id) ~ '/?force=true' }}"
    method: DELETE
    HEADER_Content-type: "application/json"
    status_code: 200
  ignore_errors: true
  with_file: marathon_task_files
- name: Reload Zookeeper, Mesos, Marathon
  service: name="{{item}}" state=reloaded
  with_items:
    - zookeeper
    - mesos-master
    - marathon
    - mesos-slave
  when: not var_marathon_installation|skipped
- name: "Wait for ports to become available (Zookeeper, Mesos, Marathon)"
  wait_for: >
    port={{item}}
    host={{ansible_default_ipv4.address}}
    delay=2
  with_items:
    - 5050
    - 8080
    - 2181

