---
- set_fact:
    path_tmp_build_nginx: /tmp/build-nginx.docker/
- name: Recreate temporary build directory
  file: "path={{path_tmp_build_nginx}} state={{item}}"
  with_items:
    - absent
    - directory
- name: Render configuration file templates
  template: src=./django.conf.j2 dest="{{path_tmp_build_nginx|os_path_join('django.conf')}}"
- name: Copy Dockerfile
  copy: src=Dockerfile dest="{{path_tmp_build_nginx|os_path_join('Dockerfile')}}"
- name: Build Nginx Docker image
  docker_image: >
    path={{path_tmp_build_nginx}} 
    name=django_mesos_example_nginx 
    state=present 
    tag={{nginx_docker_image_version_tag}}
- name: Remove temporary build directory
  file: "path={{path_tmp_build_nginx}} state=absent"
