---    
- name: "[Mesosphere] Add Mesosphere APT key"
  apt_key: keyserver=keyserver.ubuntu.com id=E56151BF state=present
- name: "[OS] Get distribution info"
  shell: "lsb_release -is | tr '[:upper:]' '[:lower:]'"
  register: var_os_distribution
- name: "[OS] Get LSB release"
  shell: "lsb_release -cs"
  register: var_os_codename
- name: "[Mesosphere] Add APT repository"
  apt_repository: >
    repo="deb http://repos.mesosphere.com/{{ var_os_distribution.stdout }} {{ var_os_codename.stdout }} main"
    state=present 
    update_cache=yes

