# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160306_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatesnippet',
            name='uuid',
        ),
    ]
